name: Build Debian Package with FPM

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install FPM
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-dev rubygems gcc make
        sudo gem install --no-document fpm

    - name: Build Debian package with FPM
      run: |
        # Here's a simple example to create a Debian package for a Python script
        # Adjust the fpm command as per your specific requirements
        ls -al

